### PR TITLE
Fixed `cooldown` requirement

### PR DESCRIPTION
**Pull request by Baterka**
Fixed:
 - Requirement `cooldown` was not working properly
 
Added:
 - Clarification that `cooldown` requirement values are in seconds.

Refactors:
 - Minor refactors to `BlockListener.process` method for better readability

### CODE REVIEW

**Comment by Baterka** [comment]
I just realized that I kinda broke tests for `CheckPhase` class. I think that it would be better to actually do some refactor there as the `CheckPhase` class does not make much sense to me and we should probably test whole `BlockListener.process()` method instead of just fragmenting it and testing only parts of the logic.

**Review by tastybento — CHANGES_REQUESTED** [review]
The purpose of the CheckPhase class was explicitly to pull out the logic for determining the next phase and related methods so they could be tested and the logic verified. That code was originally in BlockListener but trying to test just that part is very hard. By breaking it out, it was testable. You pulled it all back in, so now it's not testable. So, it's up to you, if you want to keep it in, then find a way to test the logic and pass tests like in the CheckPhase class, or pull it back out back into CheckPhase so you can verify it works. Or come up with another way to do this. :-) The main thing is that we must have a test that verifies that phases will correctly move from one to the next.

**Comment by Baterka** [comment]
Got it. Will do.

**Comment by tastybento** [comment]
Thanks!

**Pull request merged**
